"""foundation

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 20:58:13.335172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('vat_registered', sa.Boolean(), nullable=False),
    sa.Column('vat_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vat_period', sa.Enum('monthly', 'quarterly', native_enum=False), nullable=False),
    sa.Column('weekend_days', sa.JSON(), nullable=False),
    sa.Column('tax_id_pattern', sa.String(length=100), nullable=False),
    sa.Column('default_date_format', sa.String(length=3), nullable=False),
    sa.Column('min_cash_buffer_minor', sa.BigInteger(), nullable=False),
    sa.Column('min_cash_buffer_currency', sa.String(length=3), nullable=False),
    sa.Column('demo_mode', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('asset', 'liability', 'equity', 'income', 'expense', native_enum=False), nullable=False),
    sa.Column('is_bank', sa.Boolean(), nullable=False),
    sa.Column('is_inventory', sa.Boolean(), nullable=False),
    sa.Column('is_vat_input', sa.Boolean(), nullable=False),
    sa.Column('is_vat_output', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_code'), ['code'], unique=False)

    op.create_table('action',
    sa.Column('agent', sa.Enum('stock', 'cashflow', 'accountant', 'harness', native_enum=False), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('graph_name', sa.String(length=60), nullable=False),
    sa.Column('graph_thread_id', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('risk_class', sa.Enum('read_only', 'reversible', 'irreversible_external', native_enum=False), nullable=False),
    sa.Column('stage', sa.Enum('planned', 'prechecked', 'awaiting_approval', 'executing', 'verifying', 'completed', 'rolled_back', 'retrying', 'escalated', 'failed', 'rejected', native_enum=False), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('parent_action_id', sa.Uuid(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('verifier_verdict', sa.JSON(), nullable=True),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['parent_action_id'], ['action.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_graph_thread_id'), ['graph_thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_type'), ['type'], unique=False)

    op.create_table('agent_calibration',
    sa.Column('agent', sa.String(length=20), nullable=False),
    sa.Column('metric', sa.String(length=60), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('high_confidence_threshold', sa.Float(), nullable=False),
    sa.Column('low_confidence_threshold', sa.Float(), nullable=False),
    sa.Column('auto_approve_factor', sa.Float(), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('degraded_since', sa.Date(), nullable=True),
    sa.Column('healthy_streak', sa.Integer(), nullable=False),
    sa.Column('restore_progress', sa.Float(), nullable=False),
    sa.Column('method_override', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'agent', 'metric')
    )
    with op.batch_alter_table('agent_calibration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_calibration_business_id'), ['business_id'], unique=False)

    op.create_table('agent_calibration_history',
    sa.Column('agent', sa.String(length=20), nullable=False),
    sa.Column('metric', sa.String(length=60), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('high_confidence_threshold', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_calibration_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_calibration_history_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_calibration_history_date'), ['date'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=True),
    sa.Column('business_time', sa.DateTime(), nullable=False),
    sa.Column('wall_time', sa.DateTime(), nullable=False),
    sa.Column('agent', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action_id', sa.Uuid(), nullable=True),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=False),
    sa.Column('verification_result', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_business_time'), ['business_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_event'), ['event'], unique=False)

    op.create_table('bank_account',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('bank', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_cash_on_hand', sa.Boolean(), nullable=False),
    sa.Column('ledger_account_code', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_account_business_id'), ['business_id'], unique=False)

    op.create_table('business_clock',
    sa.Column('mode', sa.Enum('real', 'simulated', native_enum=False), nullable=False),
    sa.Column('current_date', sa.Date(), nullable=False),
    sa.Column('last_run_date', sa.Date(), nullable=True),
    sa.Column('advancing', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    with op.batch_alter_table('business_clock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_clock_business_id'), ['business_id'], unique=False)

    op.create_table('event',
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('producer', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('action_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('dispatched', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_dispatched'), ['dispatched'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_type'), ['type'], unique=False)

    op.create_table('feed_override',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('overrides', sa.JSON(), nullable=False),
    sa.Column('chaos_injection_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'date')
    )
    with op.batch_alter_table('feed_override', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_override_business_id'), ['business_id'], unique=False)

    op.create_table('incident',
    sa.Column('agent', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('detected_by', sa.String(length=60), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('open', 'investigating', 'resolved', 'wont_fix', native_enum=False), nullable=False),
    sa.Column('refs', sa.JSON(), nullable=False),
    sa.Column('action_id', sa.Uuid(), nullable=True),
    sa.Column('chaos_injection_id', sa.Uuid(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_chaos_injection_id'), ['chaos_injection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_type'), ['type'], unique=False)

    op.create_table('learned_rule',
    sa.Column('agent', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.Enum('precondition', 'check', 'parsing_hint', 'classification', 'policy', native_enum=False), nullable=False),
    sa.Column('rule_text_en', sa.Text(), nullable=False),
    sa.Column('rule_text_ar', sa.Text(), nullable=False),
    sa.Column('trigger', sa.JSON(), nullable=False),
    sa.Column('source_incident_id', sa.Uuid(), nullable=True),
    sa.Column('proposed_by', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('proposed', 'active', 'rejected', 'inactive', native_enum=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('previous_version_id', sa.Uuid(), nullable=True),
    sa.Column('times_applied', sa.Integer(), nullable=False),
    sa.Column('times_overridden', sa.Integer(), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learned_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learned_rule_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learned_rule_status'), ['status'], unique=False)

    op.create_table('sale',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('amount_total_minor', sa.BigInteger(), nullable=False),
    sa.Column('amount_total_currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'card', 'transfer', 'credit', native_enum=False), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('import_batch_id', sa.String(length=64), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=True),
    sa.Column('stock_applied', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_row_hash'), ['row_hash'], unique=False)

    op.create_table('setting',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'key')
    )
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setting_business_id'), ['business_id'], unique=False)

    op.create_table('supplier',
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('vat_number', sa.String(length=40), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telegram', sa.String(length=80), nullable=True),
    sa.Column('stated_lead_time_days', sa.Integer(), nullable=False),
    sa.Column('observed_lead_time_days', sa.Float(), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('early_payment_discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('early_payment_days', sa.Integer(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('date_format_hint', sa.Enum('DMY', 'MDY', native_enum=False), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_business_id'), ['business_id'], unique=False)

    op.create_table('user',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('staff', 'manager', 'owner', native_enum=False), nullable=False),
    sa.Column('language', sa.Enum('en', 'ar', native_enum=False), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('telegram_link_code', sa.String(length=16), nullable=True),
    sa.Column('telegram_link_expires', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'username'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_business_id'), ['business_id'], unique=False)

    op.create_table('approval_request',
    sa.Column('action_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('approval', 'question', 'alert', native_enum=False), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.Column('text_ar', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('required_role', sa.String(length=10), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('safe_default', sa.String(length=40), nullable=True),
    sa.Column('urgency', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'resolved', 'timed_out', 'superseded', native_enum=False), nullable=False),
    sa.Column('resolved_option', sa.String(length=40), nullable=True),
    sa.Column('resolved_edits', sa.JSON(), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_via', sa.Enum('dashboard', 'telegram', 'system', native_enum=False), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('reask_count', sa.Integer(), nullable=False),
    sa.Column('telegram_message_refs', sa.JSON(), nullable=False),
    sa.Column('graph_name', sa.String(length=60), nullable=True),
    sa.Column('graph_thread_id', sa.String(length=100), nullable=True),
    sa.Column('gate_key', sa.String(length=80), nullable=False),
    sa.Column('interrupt_id', sa.String(length=100), nullable=True),
    sa.Column('request_token', sa.String(length=32), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('agent', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_thread_id', 'gate_key'),
    sa.UniqueConstraint('request_token')
    )
    with op.batch_alter_table('approval_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_request_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_request_status'), ['status'], unique=False)

    op.create_table('bank_balance_snapshot',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('balance_minor', sa.BigInteger(), nullable=False),
    sa.Column('balance_currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_account.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_balance_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_balance_snapshot_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_balance_snapshot_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_balance_snapshot_business_id'), ['business_id'], unique=False)

    op.create_table('bank_transaction',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('amount_currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('import_batch_id', sa.String(length=64), nullable=False),
    sa.Column('match_status', sa.Enum('unmatched', 'suggested', 'auto_matched', 'confirmed', 'excluded', native_enum=False), nullable=False),
    sa.Column('matched_type', sa.String(length=40), nullable=True),
    sa.Column('matched_id', sa.Uuid(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('match_source', sa.String(length=30), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_account.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_transaction_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transaction_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transaction_date'), ['date'], unique=False)

    op.create_table('check_result',
    sa.Column('action_id', sa.Uuid(), nullable=True),
    sa.Column('extraction_id', sa.Uuid(), nullable=True),
    sa.Column('check_name', sa.String(length=60), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('learned_rule_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('check_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_check_result_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_check_result_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_check_result_extraction_id'), ['extraction_id'], unique=False)

    op.create_table('event_delivery',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('consumer', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('handled', 'failed', native_enum=False), nullable=False),
    sa.Column('handled_at', sa.DateTime(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'consumer')
    )
    with op.batch_alter_table('event_delivery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_delivery_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_delivery_event_id'), ['event_id'], unique=False)

    op.create_table('file_ref',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_ref', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_ref_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_ref_sha256'), ['sha256'], unique=False)

    op.create_table('item',
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('is_ingredient', sa.Boolean(), nullable=False),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('reorder_point', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('safety_stock', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('storage_capacity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('preferred_supplier_id', sa.Uuid(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('unit_cost_minor', sa.BigInteger(), nullable=False),
    sa.Column('unit_cost_currency', sa.String(length=3), nullable=False),
    sa.Column('sale_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('sale_price_currency', sa.String(length=3), nullable=False),
    sa.Column('margin_class', sa.Enum('high', 'normal', 'low', native_enum=False), nullable=False),
    sa.Column('forecast_method', sa.Enum('holt_winters', 'same_weekday_avg', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['preferred_supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_business_id'), ['business_id'], unique=False)

    op.create_table('obligation',
    sa.Column('type', sa.Enum('rent', 'salary', 'loan', 'tax', 'utility', 'subscription', 'other', native_enum=False), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('amount_currency', sa.String(length=3), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('recurrence', sa.Enum('monthly', 'quarterly', 'annual', 'once', native_enum=False), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('last_seen_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('bank_account_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('obligation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obligation_business_id'), ['business_id'], unique=False)

    op.create_table('supplier_alias',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('alias_text', sa.String(length=200), nullable=False),
    sa.Column('normalised_text', sa.String(length=200), nullable=False),
    sa.Column('language', sa.Enum('en', 'ar', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_alias_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_alias_normalised_text'), ['normalised_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_alias_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('recipe_line',
    sa.Column('sold_item_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['ingredient_item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['sold_item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_line_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_line_sold_item_id'), ['sold_item_id'], unique=False)

    op.create_table('supplier_price',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('pack_size', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('min_order_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price_minor', sa.BigInteger(), nullable=False),
    sa.Column('price_currency', sa.String(length=3), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_price', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_price_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_price_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_price_supplier_id'), ['supplier_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_price', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_price_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_price_item_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_price_business_id'))

    op.drop_table('supplier_price')
    with op.batch_alter_table('recipe_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_line_sold_item_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_line_business_id'))

    op.drop_table('recipe_line')
    with op.batch_alter_table('supplier_alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_alias_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_alias_normalised_text'))
        batch_op.drop_index(batch_op.f('ix_supplier_alias_business_id'))

    op.drop_table('supplier_alias')
    with op.batch_alter_table('obligation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_obligation_business_id'))

    op.drop_table('obligation')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_business_id'))

    op.drop_table('item')
    with op.batch_alter_table('file_ref', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_ref_sha256'))
        batch_op.drop_index(batch_op.f('ix_file_ref_business_id'))

    op.drop_table('file_ref')
    with op.batch_alter_table('event_delivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_delivery_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_delivery_business_id'))

    op.drop_table('event_delivery')
    with op.batch_alter_table('check_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_check_result_extraction_id'))
        batch_op.drop_index(batch_op.f('ix_check_result_business_id'))
        batch_op.drop_index(batch_op.f('ix_check_result_action_id'))

    op.drop_table('check_result')
    with op.batch_alter_table('bank_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_bank_transaction_business_id'))
        batch_op.drop_index(batch_op.f('ix_bank_transaction_account_id'))

    op.drop_table('bank_transaction')
    with op.batch_alter_table('bank_balance_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_balance_snapshot_business_id'))
        batch_op.drop_index(batch_op.f('ix_bank_balance_snapshot_as_of'))
        batch_op.drop_index(batch_op.f('ix_bank_balance_snapshot_account_id'))

    op.drop_table('bank_balance_snapshot')
    with op.batch_alter_table('approval_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_request_status'))
        batch_op.drop_index(batch_op.f('ix_approval_request_business_id'))

    op.drop_table('approval_request')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_business_id'))

    op.drop_table('user')
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_business_id'))

    op.drop_table('supplier')
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setting_business_id'))

    op.drop_table('setting')
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_row_hash'))
        batch_op.drop_index(batch_op.f('ix_sale_date'))
        batch_op.drop_index(batch_op.f('ix_sale_business_id'))

    op.drop_table('sale')
    with op.batch_alter_table('learned_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learned_rule_status'))
        batch_op.drop_index(batch_op.f('ix_learned_rule_business_id'))

    op.drop_table('learned_rule')
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_type'))
        batch_op.drop_index(batch_op.f('ix_incident_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_incident_chaos_injection_id'))
        batch_op.drop_index(batch_op.f('ix_incident_business_id'))

    op.drop_table('incident')
    with op.batch_alter_table('feed_override', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_override_business_id'))

    op.drop_table('feed_override')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_type'))
        batch_op.drop_index(batch_op.f('ix_event_dispatched'))
        batch_op.drop_index(batch_op.f('ix_event_business_id'))

    op.drop_table('event')
    with op.batch_alter_table('business_clock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_clock_business_id'))

    op.drop_table('business_clock')
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_account_business_id'))

    op.drop_table('bank_account')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_event'))
        batch_op.drop_index(batch_op.f('ix_audit_log_business_time'))
        batch_op.drop_index(batch_op.f('ix_audit_log_business_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action_id'))

    op.drop_table('audit_log')
    with op.batch_alter_table('agent_calibration_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_calibration_history_date'))
        batch_op.drop_index(batch_op.f('ix_agent_calibration_history_business_id'))

    op.drop_table('agent_calibration_history')
    with op.batch_alter_table('agent_calibration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_calibration_business_id'))

    op.drop_table('agent_calibration')
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_type'))
        batch_op.drop_index(batch_op.f('ix_action_graph_thread_id'))
        batch_op.drop_index(batch_op.f('ix_action_business_id'))

    op.drop_table('action')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_code'))
        batch_op.drop_index(batch_op.f('ix_account_business_id'))

    op.drop_table('account')
    op.drop_table('business')
    # ### end Alembic commands ###
