"""stock

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-28 21:38:49.253766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_order',
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'sent', 'partially_received', 'received', 'closed', 'rejected', 'on_hold', 'cancelled', native_enum=False), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('total_currency', sa.String(length=3), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('is_critical_order', sa.Boolean(), nullable=False),
    sa.Column('created_by_action_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approval_request_id', sa.Uuid(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('merged_into_id', sa.Uuid(), nullable=True),
    sa.Column('late_flagged', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('delivery',
    sa.Column('po_id', sa.Uuid(), nullable=False),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('received_by', sa.Uuid(), nullable=True),
    sa.Column('photo_file_id', sa.Uuid(), nullable=True),
    sa.Column('discrepancies', sa.JSON(), nullable=False),
    sa.Column('action_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['photo_file_id'], ['file_ref.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_po_id'), ['po_id'], unique=False)

    op.create_table('demand_forecast',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('expected', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('method', sa.Enum('holt_winters', 'same_weekday_avg', 'derived', native_enum=False), nullable=False),
    sa.Column('generated_on', sa.Date(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'forecast_date', 'generated_on')
    )
    with op.batch_alter_table('demand_forecast', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demand_forecast_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_forecast_forecast_date'), ['forecast_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_forecast_generated_on'), ['generated_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_forecast_item_id'), ['item_id'], unique=False)

    op.create_table('purchase_order_line',
    sa.Column('po_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('pack_size', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('unit_price_currency', sa.String(length=3), nullable=False),
    sa.Column('line_total_minor', sa.BigInteger(), nullable=False),
    sa.Column('line_total_currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_line_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_line_po_id'), ['po_id'], unique=False)

    op.create_table('stock_count',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('counted_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('calculated_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('variance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('counted_by', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('resolution', sa.Enum('accepted', 'investigating', 'adjusted', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_count', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_count_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_count_item_id'), ['item_id'], unique=False)

    op.create_table('stock_level',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('location', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('last_counted_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'location')
    )
    with op.batch_alter_table('stock_level', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_level_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_level_item_id'), ['item_id'], unique=False)

    op.create_table('stock_movement',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('location', sa.String(length=40), nullable=False),
    sa.Column('type', sa.Enum('sale', 'purchase', 'waste', 'spoilage', 'adjustment', 'transfer', 'count_correction', native_enum=False), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('action_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movement_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movement_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movement_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movement_reference_id'), ['reference_id'], unique=False)

    op.create_table('delivery_line',
    sa.Column('delivery_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price_on_note_minor', sa.BigInteger(), nullable=False),
    sa.Column('unit_price_on_note_currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_line_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_line_delivery_id'), ['delivery_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_line_delivery_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_line_business_id'))

    op.drop_table('delivery_line')
    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movement_reference_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movement_item_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movement_date'))
        batch_op.drop_index(batch_op.f('ix_stock_movement_business_id'))

    op.drop_table('stock_movement')
    with op.batch_alter_table('stock_level', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_level_item_id'))
        batch_op.drop_index(batch_op.f('ix_stock_level_business_id'))

    op.drop_table('stock_level')
    with op.batch_alter_table('stock_count', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_count_item_id'))
        batch_op.drop_index(batch_op.f('ix_stock_count_business_id'))

    op.drop_table('stock_count')
    with op.batch_alter_table('purchase_order_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_line_po_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_line_business_id'))

    op.drop_table('purchase_order_line')
    with op.batch_alter_table('demand_forecast', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demand_forecast_item_id'))
        batch_op.drop_index(batch_op.f('ix_demand_forecast_generated_on'))
        batch_op.drop_index(batch_op.f('ix_demand_forecast_forecast_date'))
        batch_op.drop_index(batch_op.f('ix_demand_forecast_business_id'))

    op.drop_table('demand_forecast')
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_po_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_business_id'))

    op.drop_table('delivery')
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_number'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_business_id'))

    op.drop_table('purchase_order')
    # ### end Alembic commands ###
