"""books

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-28 22:00:08.562792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entry',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=False),
    sa.Column('reference_id', sa.String(length=80), nullable=True),
    sa.Column('memo', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('posted', 'quarantined', 'reversed', native_enum=False), nullable=False),
    sa.Column('reverses_id', sa.Uuid(), nullable=True),
    sa.Column('action_id', sa.Uuid(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entry_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_reference_type'), ['reference_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_status'), ['status'], unique=False)

    op.create_table('receivable_invoice',
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_contact', sa.String(length=200), nullable=True),
    sa.Column('customer_telegram', sa.String(length=80), nullable=True),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('subtotal_minor', sa.BigInteger(), nullable=False),
    sa.Column('subtotal_currency', sa.String(length=3), nullable=False),
    sa.Column('vat_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('vat_amount_currency', sa.String(length=3), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('total_currency', sa.String(length=3), nullable=False),
    sa.Column('amount_paid_minor', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('open', 'partially_paid', 'paid', 'void', native_enum=False), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('late_payment_history_score', sa.Float(), nullable=False),
    sa.Column('journal_entry_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'number')
    )
    with op.batch_alter_table('receivable_invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receivable_invoice_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receivable_invoice_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_receivable_invoice_status'), ['status'], unique=False)

    op.create_table('classification_correction',
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('from_account_id', sa.Uuid(), nullable=True),
    sa.Column('to_account_id', sa.Uuid(), nullable=False),
    sa.Column('corrected_by', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source_ref', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classification_correction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classification_correction_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classification_correction_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('journal_line',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('debit_minor', sa.BigInteger(), nullable=False),
    sa.Column('credit_minor', sa.BigInteger(), nullable=False),
    sa.Column('memo', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_line_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_line_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_line_entry_id'), ['entry_id'], unique=False)

    op.create_table('document',
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.Enum('dashboard', 'telegram', native_enum=False), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('language_detected', sa.Enum('en', 'ar', 'bilingual', native_enum=False), nullable=True),
    sa.Column('status', sa.Enum('received', 'extracting', 'extracted', 'needs_review', 'posted', 'rejected', 'duplicate', native_enum=False), nullable=False),
    sa.Column('document_confidence', sa.Float(), nullable=True),
    sa.Column('graph_thread_id', sa.String(length=100), nullable=True),
    sa.Column('payable_invoice_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file_ref.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_status'), ['status'], unique=False)

    op.create_table('extraction',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('document_confidence', sa.Float(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('verifier_verdict', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_document_id'), ['document_id'], unique=False)

    op.create_table('payable_invoice',
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_number', sa.String(length=60), nullable=False),
    sa.Column('normalised_number', sa.String(length=60), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('subtotal_minor', sa.BigInteger(), nullable=False),
    sa.Column('subtotal_currency', sa.String(length=3), nullable=False),
    sa.Column('vat_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('vat_amount_currency', sa.String(length=3), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('total_currency', sa.String(length=3), nullable=False),
    sa.Column('supplier_vat_number', sa.String(length=40), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'held', 'posted', 'paid', 'void', native_enum=False), nullable=False),
    sa.Column('hold_reason', sa.JSON(), nullable=True),
    sa.Column('match_result', sa.JSON(), nullable=True),
    sa.Column('amount_paid_minor', sa.BigInteger(), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.Column('journal_entry_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payable_invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payable_invoice_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payable_invoice_normalised_number'), ['normalised_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_payable_invoice_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payable_invoice_supplier_id'), ['supplier_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payable_invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payable_invoice_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_payable_invoice_status'))
        batch_op.drop_index(batch_op.f('ix_payable_invoice_normalised_number'))
        batch_op.drop_index(batch_op.f('ix_payable_invoice_business_id'))

    op.drop_table('payable_invoice')
    with op.batch_alter_table('extraction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_document_id'))
        batch_op.drop_index(batch_op.f('ix_extraction_business_id'))

    op.drop_table('extraction')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_status'))
        batch_op.drop_index(batch_op.f('ix_document_sha256'))
        batch_op.drop_index(batch_op.f('ix_document_business_id'))

    op.drop_table('document')
    with op.batch_alter_table('journal_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_line_entry_id'))
        batch_op.drop_index(batch_op.f('ix_journal_line_business_id'))
        batch_op.drop_index(batch_op.f('ix_journal_line_account_id'))

    op.drop_table('journal_line')
    with op.batch_alter_table('classification_correction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classification_correction_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_classification_correction_business_id'))

    op.drop_table('classification_correction')
    with op.batch_alter_table('receivable_invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receivable_invoice_status'))
        batch_op.drop_index(batch_op.f('ix_receivable_invoice_due_date'))
        batch_op.drop_index(batch_op.f('ix_receivable_invoice_business_id'))

    op.drop_table('receivable_invoice')
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entry_status'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_reference_type'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_reference_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_date'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_business_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_action_id'))

    op.drop_table('journal_entry')
    # ### end Alembic commands ###
