"""cash

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-29 18:48:21.905607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_forecast_run',
    sa.Column('generated_on', sa.Date(), nullable=False),
    sa.Column('bank_data_as_of', sa.DateTime(), nullable=True),
    sa.Column('low_confidence_reason', sa.String(length=300), nullable=True),
    sa.Column('primary_scenario', sa.Enum('expected', 'pessimistic', 'optimistic', native_enum=False), nullable=False),
    sa.Column('opening_balance_minor', sa.BigInteger(), nullable=False),
    sa.Column('opening_balance_currency', sa.String(length=3), nullable=False),
    sa.Column('lowest_balance_minor', sa.BigInteger(), nullable=False),
    sa.Column('lowest_balance_currency', sa.String(length=3), nullable=False),
    sa.Column('lowest_date', sa.Date(), nullable=False),
    sa.Column('buffer_minor', sa.BigInteger(), nullable=False),
    sa.Column('buffer_currency', sa.String(length=3), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('flows', sa.JSON(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('action_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_forecast_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_forecast_run_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_forecast_run_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_forecast_run_generated_on'), ['generated_on'], unique=False)

    op.create_table('purchasing_budget',
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('amount_currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('tightened', sa.Boolean(), nullable=False),
    sa.Column('published_event_id', sa.Uuid(), nullable=True),
    sa.Column('forecast_run_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'week_start')
    )
    with op.batch_alter_table('purchasing_budget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchasing_budget_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchasing_budget_week_start'), ['week_start'], unique=False)

    op.create_table('cash_forecast',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('scenario', sa.Enum('expected', 'pessimistic', 'optimistic', native_enum=False), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('opening_minor', sa.BigInteger(), nullable=False),
    sa.Column('opening_currency', sa.String(length=3), nullable=False),
    sa.Column('inflows_minor', sa.BigInteger(), nullable=False),
    sa.Column('inflows_currency', sa.String(length=3), nullable=False),
    sa.Column('outflows_minor', sa.BigInteger(), nullable=False),
    sa.Column('outflows_currency', sa.String(length=3), nullable=False),
    sa.Column('closing_minor', sa.BigInteger(), nullable=False),
    sa.Column('closing_currency', sa.String(length=3), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('below_buffer', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['cash_forecast_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_forecast', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_forecast_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_forecast_run_id'), ['run_id'], unique=False)

    op.create_table('payment_promise',
    sa.Column('receivable_invoice_id', sa.Uuid(), nullable=False),
    sa.Column('promised_date', sa.Date(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('amount_currency', sa.String(length=3), nullable=False),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('outcome', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['receivable_invoice_id'], ['receivable_invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_promise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_promise_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_promise_receivable_invoice_id'), ['receivable_invoice_id'], unique=False)

    op.create_table('payment_reminder',
    sa.Column('receivable_invoice_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'pending_approval', 'sent', 'cancelled_paid', 'cancelled_owner', native_enum=False), nullable=False),
    sa.Column('cancel_reason', sa.String(length=300), nullable=True),
    sa.Column('text_en', sa.String(length=600), nullable=False),
    sa.Column('text_ar', sa.String(length=600), nullable=False),
    sa.Column('action_id', sa.Uuid(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('auto_approved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['receivable_invoice_id'], ['receivable_invoice.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receivable_invoice_id', 'level')
    )
    with op.batch_alter_table('payment_reminder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_reminder_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_reminder_receivable_invoice_id'), ['receivable_invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_reminder_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_reminder_status'), ['status'], unique=False)

    op.create_table('shortfall_plan',
    sa.Column('forecast_run_id', sa.Uuid(), nullable=False),
    sa.Column('gap_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('gap_amount_currency', sa.String(length=3), nullable=False),
    sa.Column('gap_date', sa.Date(), nullable=False),
    sa.Column('lowest_balance_minor', sa.BigInteger(), nullable=False),
    sa.Column('lowest_balance_currency', sa.String(length=3), nullable=False),
    sa.Column('lowest_date', sa.Date(), nullable=False),
    sa.Column('days_to_act', sa.Integer(), nullable=False),
    sa.Column('combined_lowest_balance_minor', sa.BigInteger(), nullable=False),
    sa.Column('combined_lowest_balance_currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'presented', 'accepted', 'dismissed', 'superseded', native_enum=False), nullable=False),
    sa.Column('graph_thread_id', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['cash_forecast_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shortfall_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shortfall_plan_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shortfall_plan_forecast_run_id'), ['forecast_run_id'], unique=False)

    op.create_table('plan_action',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('chase_receivable', 'delay_payable', 'defer_po', 'move_expense', 'financing', native_enum=False), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_ref', sa.String(length=80), nullable=True),
    sa.Column('description_en', sa.String(length=300), nullable=False),
    sa.Column('description_ar', sa.String(length=300), nullable=False),
    sa.Column('impact_minor', sa.BigInteger(), nullable=False),
    sa.Column('impact_currency', sa.String(length=3), nullable=False),
    sa.Column('risk', sa.Enum('low', 'medium', 'high', native_enum=False), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('simulated_lowest_balance_minor', sa.BigInteger(), nullable=False),
    sa.Column('simulated_lowest_balance_currency', sa.String(length=3), nullable=False),
    sa.Column('simulated_lowest_date', sa.Date(), nullable=False),
    sa.Column('adjustments', sa.JSON(), nullable=False),
    sa.Column('simulated_series', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'accepted', 'declined', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['shortfall_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_action_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_action_plan_id'), ['plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_action_plan_id'))
        batch_op.drop_index(batch_op.f('ix_plan_action_business_id'))

    op.drop_table('plan_action')
    with op.batch_alter_table('shortfall_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shortfall_plan_forecast_run_id'))
        batch_op.drop_index(batch_op.f('ix_shortfall_plan_business_id'))

    op.drop_table('shortfall_plan')
    with op.batch_alter_table('payment_reminder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_reminder_status'))
        batch_op.drop_index(batch_op.f('ix_payment_reminder_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_payment_reminder_receivable_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_payment_reminder_business_id'))

    op.drop_table('payment_reminder')
    with op.batch_alter_table('payment_promise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_promise_receivable_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_payment_promise_business_id'))

    op.drop_table('payment_promise')
    with op.batch_alter_table('cash_forecast', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_forecast_run_id'))
        batch_op.drop_index(batch_op.f('ix_cash_forecast_business_id'))

    op.drop_table('cash_forecast')
    with op.batch_alter_table('purchasing_budget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchasing_budget_week_start'))
        batch_op.drop_index(batch_op.f('ix_purchasing_budget_business_id'))

    op.drop_table('purchasing_budget')
    with op.batch_alter_table('cash_forecast_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_forecast_run_generated_on'))
        batch_op.drop_index(batch_op.f('ix_cash_forecast_run_business_id'))
        batch_op.drop_index(batch_op.f('ix_cash_forecast_run_action_id'))

    op.drop_table('cash_forecast_run')
    # ### end Alembic commands ###
