"""WHERE THE KIT IS ALLOWED TO ATTACH A TRACE HEADER.

The kit already stands inside the host's outgoing HTTP call — it is holding the
request to measure it. Attaching the three trace headers while it is there is
what turns a collection of single-service traces into one chain.

But an outgoing call is not necessarily a call to another part of the
customer's own system. It may be a payment provider, a model vendor, a webhook,
an analytics endpoint. Attaching a header there means an outside company
receives an identifier generated by Boosthis, on a request Boosthis had no
business modifying, and the customer never asked for that and cannot see it
happening.

So propagation is DECIDED, not assumed, and the decision is made from the
destination host alone:

  * The default permits only destinations that CANNOT be on the public
    internet — loopback, the private and carrier-grade IPv4 ranges, IPv6
    unique-local, a single-label container/service name, and the hostname
    suffixes reserved for private use. An outside company is reachable at a
    public name on a public address, so under the default it never receives
    the header.
  * A customer who runs their own services on public DNS widens it by naming
    hosts or suffixes. What they name is what they get: the list REPLACES the
    default rather than extending it, because "these destinations" is the only
    reading of an explicit list that cannot surprise anyone.
  * ``none`` switches propagation off entirely, and wins over anything else in
    the same list. The most restrictive entry always decides.

TWO DELIBERATE EXCLUSIONS FROM THE DEFAULT SET, both for the same reason — the
address is private but the machine answering is somebody else's:

  * IPv4 link-local ``169.254.0.0/16`` and IPv6 ``fe80::/10``.
    ``169.254.169.254`` is the cloud provider's instance-metadata service on
    every major host. It is not the customer's service and it is not ours to
    tag.
  * There is no ``all`` keyword. A switch meaning "send our identifier to every
    destination this app talks to" is a promise we could not make in the
    published disclosure, so it does not exist. A customer who wants a public
    destination names it.

The module is PURE and allocation-cheap: no I/O, no imports beyond the standard
library, no regular expression run per call. It is consulted once per outgoing
request on the host's own stack.

Byte-parity: ``src/tracePropagation.ts`` in the Node kit implements the same
rule with the same constants, and
``scripts/src/__tests__/trace-propagation-parity.test.ts`` holds the two to each
other and to the written coverage record.
"""

from __future__ import annotations

import os
from typing import Any, Iterable, NamedTuple, Optional, Sequence

# The one setting. Unset means DEFAULT_PROPAGATION.
PROPAGATION_ENV = "BOOSTHIS_TRACE_PROPAGATION"

# What an unset PROPAGATION_ENV means.
DEFAULT_PROPAGATION = "internal"

# The keyword for the built-in "cannot be on the public internet" set.
INTERNAL_KEYWORD = "internal"

# The keywords that switch propagation off. Either spelling, because both are
# what people type, and a setting that silently ignores the customer's attempt
# to turn something off is the worst kind of setting.
OFF_KEYWORDS: tuple[str, ...] = ("none", "off")

# Hostname suffixes reserved for private/internal use. A name ending in one of
# these cannot resolve to an outside company's service. Each is matched as the
# whole host or as a dot-preceded suffix of it, so ``.local`` covers
# ``api.local`` and Kubernetes' ``svc.cluster.local`` alike.
INTERNAL_SUFFIXES: tuple[str, ...] = (
    "localhost",
    "local",
    "internal",
    "intranet",
    "home.arpa",
    "lan",
    "test",
)

# Single-label names that DO have a public DNS answer, against the rule below
# that reads a dotless name as a container or Kubernetes short name. That
# reading is right almost always and wrong for a handful of top-level domains
# which carry address records of their own: ``ws``, ``tk`` and ``uz`` answer
# publicly today, so under the default ``http://ws/`` would leave the building
# carrying an identifier we generated. The rest have answered within living
# memory and can again.
#
# A denylist rather than the full list of registered top-level domains, on
# purpose: ``dev``, ``app``, ``cloud`` and ``zone`` are all real TLDs AND
# thoroughly ordinary internal service names, so refusing every registered TLD
# would refuse the common case in order to close the rare one.
#
# Matched as the WHOLE host, lowercased, and only against the built-in set — a
# customer whose own service really is called ``ws`` names it in their list and
# that is a recorded decision this module does not overrule.
#
# Source: the dotless-domain surveys behind ICANN SAC053. Re-checked
# 2026-09-10. Being a superset of what resolves today is the conservative
# direction: a name that stops resolving costs a customer one list entry.
PUBLIC_DOTLESS_HOSTS: tuple[str, ...] = (
    "ac",
    "ai",
    "cm",
    "dk",
    "gg",
    "hr",
    "io",
    "je",
    "kh",
    "kw",
    "mq",
    "pa",
    "ph",
    "pn",
    "sh",
    "sj",
    "su",
    "tk",
    "tm",
    "to",
    "ua",
    "uz",
    "va",
    "ws",
)

# Destinations that live INSIDE the set above but belong to the hosting
# provider rather than to the customer. Each is reachable at a name or an
# address the built-in set calls internal — ``metadata.google.internal`` ends
# in a reserved suffix, ``metadata`` is a single label, AWS's IPv6 instance
# metadata service is a unique-local address, Alibaba's sits inside CGNAT — so
# without this list the default would put a Boosthis identifier in a request to
# infrastructure the customer does not own. That is the very thing excluding
# link-local was for, and excluding link-local alone did not achieve it.
#
# Matched as the WHOLE host, lowercased. It applies only to the built-in set: a
# customer who names one of these in their own list has made a recorded
# decision, and this module does not overrule it.
#
# It cannot be complete — a provider can add an endpoint tomorrow. It closes the
# published ones, and the numeric forms below close the addresses.
PROVIDER_METADATA_HOSTS: tuple[str, ...] = (
    "metadata",  # Google Cloud, the short alias
    "metadata.google.internal",  # Google Cloud
    "metadata.goog",  # Google Cloud
    "metadata.internal",  # several providers' short form
    "instance-data",  # AWS, the documented alias for the IMDS
    "instance-data.ec2.internal",  # AWS
)

# The same services at their fixed ADDRESSES. Written here as text and compared
# as numbers, because ``fd00:0ec2::254`` is ``fd00:ec2::254`` written out and
# ``0100.0144.0144.0310`` is Alibaba's in octal — a string test would catch one
# spelling of each.
PROVIDER_METADATA_ADDRESSES: tuple[str, ...] = (
    "169.254.169.254",  # AWS, Azure, Google Cloud, Oracle, DigitalOcean
    "100.100.100.200",  # Alibaba Cloud — inside CGNAT, which the set permits
    "192.0.0.192",  # Oracle Cloud Classic
    "fd00:ec2::254",  # AWS over IPv6 — a unique-local address
)

# How many entries a customer's list may contain before the rest are refused. A
# bounded list keeps the per-call judgement bounded; a customer who needs more
# than this wants a suffix, not another hundred hosts.
MAX_PROPAGATION_ENTRIES = 64

_HOST_CHARS = frozenset("abcdefghijklmnopqrstuvwxyz0123456789-.:")


class PropagationPolicy(NamedTuple):
    """What the customer asked for, in a shape a surface can render."""

    #: True when nothing is ever attached.
    off: bool
    #: True when the built-in non-public set is permitted.
    internal: bool
    #: Exact hostnames the customer named, lowercased, in the order given.
    hosts: tuple[str, ...]
    #: Suffixes the customer named, WITHOUT the leading dot, in order.
    suffixes: tuple[str, ...]
    #: Entries that were not a bare host or a leading-dot suffix, kept so the
    #: surface can say a typo was ignored rather than silently obeying half a
    #: list. Capped, like the list itself.
    refused: tuple[str, ...]
    #: True when the setting was absent or empty, so this is the default.
    is_default: bool


#: The policy that applies when nobody has said anything.
_DEFAULT_POLICY = PropagationPolicy(False, True, (), (), (), True)

#: Nothing is attached, anywhere. Used for an explicit ``none`` and as the
#: fail-safe when reading the setting raises.
_OFF_POLICY = PropagationPolicy(True, False, (), (), (), False)


def _looks_like_host(value: str) -> bool:
    """A hostname may contain only these characters.

    Deliberately strict: anything with a scheme, a port, a path, a wildcard or
    whitespace is a mistake, and a mistake that is obeyed approximately is
    worse than one that is refused. A colon is allowed because a customer may
    legitimately name an IPv6 literal.
    """
    if not value or len(value) > 253:
        return False
    return all(ch in _HOST_CHARS for ch in value)


def parse_trace_propagation(raw: Any) -> PropagationPolicy:
    """Read one setting value into a policy.

    Never raises. An unreadable or nonsense value degrades to the DEFAULT, not
    to "everything": the failure mode of a misread setting must be the
    conservative one.
    """
    if raw is None:
        return _DEFAULT_POLICY
    text = str(raw).strip()
    if not text:
        return _DEFAULT_POLICY

    internal = False
    hosts: list[str] = []
    suffixes: list[str] = []
    refused: list[str] = []
    seen = 0

    for piece in text.split(","):
        entry = piece.strip().lower()
        if not entry:
            continue
        # The most restrictive entry decides, wherever it appears in the list.
        # A customer who wrote `none` meant it, even if they left older entries
        # beside it.
        if entry in OFF_KEYWORDS:
            return _OFF_POLICY
        seen += 1
        if seen > MAX_PROPAGATION_ENTRIES:
            if len(refused) < MAX_PROPAGATION_ENTRIES:
                refused.append(entry)
            continue
        if entry == INTERNAL_KEYWORD:
            internal = True
            continue
        if entry.startswith("."):
            suffix = entry[1:]
            if suffix and _looks_like_host(suffix):
                suffixes.append(suffix)
            else:
                refused.append(entry)
            continue
        if _looks_like_host(entry):
            hosts.append(entry)
        else:
            refused.append(entry)

    # A list of nothing but refusals is a list the customer meant to widen
    # something with. Falling back to the default is right — it is what they
    # had before they typed it — and the refused entries are on the surface so
    # they can see why nothing changed.
    if not internal and not hosts and not suffixes:
        return PropagationPolicy(False, True, (), (), tuple(refused), True)

    return PropagationPolicy(
        False, internal, tuple(hosts), tuple(suffixes), tuple(refused), False
    )


_cached: Optional[PropagationPolicy] = None


def trace_propagation_policy() -> PropagationPolicy:
    """The policy in force, read from the environment once and remembered.

    The setting is read at most once per process because this sits on the
    host's outgoing-call path, and an environment read there is a cost the host
    did not ask for. Never raises.
    """
    global _cached
    if _cached is not None:
        return _cached
    try:
        _cached = parse_trace_propagation(os.environ.get(PROPAGATION_ENV))
    except Exception:  # noqa: BLE001
        # A host that has made the environment unreadable gets the fail-safe
        # answer, not the permissive one.
        _cached = _OFF_POLICY
    return _cached


def reset_trace_propagation_policy() -> None:
    """Forget the remembered policy — for tests, and for an app that changes
    the setting after start-up and wants it re-read."""
    global _cached
    _cached = None


_DEC_DIGITS = "0123456789"
_HEX_DIGITS = "0123456789abcdefABCDEF"


def _is_numeric_address_form(host: str) -> bool:
    """True when a RESOLVER will read ``host`` as a number, not as a name.

    ``inet_aton`` — which is what the resolver ends up using — accepts one to
    four dot-separated parts, each written in decimal, octal (a leading zero)
    or hexadecimal (a leading ``0x``). So ``010.010.010.010`` and ``134744072``
    and ``0x8.0x8.0x8.0x8`` are all 8.8.8.8, and ``2852039166`` is the cloud
    metadata address. Only a part that is not a number in any of those bases
    makes the whole thing a name.
    """
    parts = host.split(".")
    if not 1 <= len(parts) <= 4:
        return False
    for part in parts:
        hexed = part[:2] in ("0x", "0X")
        body = part[2:] if hexed else part
        if not body:
            return False
        allowed = _HEX_DIGITS if hexed else _DEC_DIGITS
        if any(ch not in allowed for ch in body):
            return False
    return True


def _read_ipv4(host: str) -> Optional[Sequence[int]]:
    """Parse a dotted quad in its ONE canonical spelling, or None.

    Strict on purpose: exactly four parts, ASCII decimal, and no leading zero
    on a longer part. Every other numeric spelling of an address is refused by
    :func:`is_internal_host` rather than canonicalised here, because the only
    safe rule is that the address the resolver reaches is the address this
    judged. ``part.isdigit()`` is not that rule — it is true of Arabic-Indic
    digits, which ``int()`` reads as a number and a resolver reads as a name.
    """
    parts = host.split(".")
    if len(parts) != 4:
        return None
    out: list[int] = []
    for part in parts:
        if not part or len(part) > 3:
            return None
        if any(ch not in _DEC_DIGITS for ch in part):
            return None
        if len(part) > 1 and part[0] == "0":
            return None  # octal to the resolver, decimal to us
        value = int(part)
        if value > 255:
            return None
        out.append(value)
    return out


def _read_hex_group(text: str) -> int:
    """Read ONE IPv6 group as a number, or -1.

    Used to compare an address rather than its spelling: ``fd00:0ec2::254`` and
    ``fd00:ec2::254`` are the same address, and a string test would catch only
    one of them.
    """
    if not text or len(text) > 4:
        return -1
    value = 0
    for ch in text:
        digit = _HEX_DIGITS.find(ch.lower())
        if digit < 0:
            return -1
        value = value * 16 + digit
    return value


def is_provider_metadata_host(host: str) -> bool:
    """True when ``host`` is a hosting provider's instance metadata service.

    Checked BEFORE the built-in set, and only against it. See
    :data:`PROVIDER_METADATA_HOSTS` for why: these destinations sit inside the
    private ranges by design, so the set that means "cannot be an outside
    company" would otherwise permit them.

    The cost is stated rather than hidden: a customer whose own service is
    genuinely called ``metadata`` loses propagation to it under the default and
    has to name it in their list. That is the safe direction.
    """
    if not host:
        return False
    bare = host[1:-1] if host.startswith("[") and host.endswith("]") else host
    bare = bare.lstrip("[")

    if bare in PROVIDER_METADATA_HOSTS:
        return True

    if ":" in bare:
        # Only the first two groups are compared, so the whole of
        # ``fd00:ec2::/32`` is refused rather than one address in it. They can
        # never be elided: an address that starts with ``::`` has zeros there
        # and is not one of these.
        groups = bare.split(":")
        first = _read_hex_group(groups[0])
        second = _read_hex_group(groups[1] if len(groups) > 1 else "")
        if first < 0 or second < 0:
            return False
        for address in PROVIDER_METADATA_ADDRESSES:
            if ":" not in address:
                continue
            parts = address.split(":")
            if _read_hex_group(parts[0]) == first and _read_hex_group(parts[1]) == second:
                return True
        return False

    quad = _read_ipv4(bare)
    if quad is None:
        return False
    for address in PROVIDER_METADATA_ADDRESSES:
        if ":" in address:
            continue
        listed = _read_ipv4(address)
        if listed is not None and tuple(listed) == tuple(quad):
            return True
    # The built-in set already excludes all of 169.254.0.0/16, where five
    # providers answer. The reason lives here too, so a later widening of that
    # range cannot reopen this door by accident.
    return quad[0] == 169 and quad[1] == 254


def is_internal_host(host: str) -> bool:
    """True when ``host`` cannot be an outside company's service.

    The built-in default set. Public because the coverage record and the
    customer-facing surface both quote it, and a rule the customer is shown
    must be the rule that runs.
    """
    if not host:
        return False

    # THE HOSTING PROVIDER IS NOT THE CUSTOMER. Decided first, because every one
    # of these destinations would pass one of the rules below.
    if is_provider_metadata_host(host):
        return False

    # IPv6, with or without the brackets an origin carries.
    if host.startswith("[") or ":" in host:
        bare = host[1:-1] if host.startswith("[") and host.endswith("]") else host
        bare = bare.lstrip("[")
        if bare == "::1":
            return True
        # Unique-local fc00::/7 — the FIRST BYTE is 0xfc or 0xfd, which in text
        # means a first group of exactly four hex digits beginning fc or fd.
        # The length test is the whole point: `fce:1234::1` also begins "fc",
        # but its first group is three digits, so the first byte is 0x0f and
        # the address is public. A prefix test alone would have handed a
        # stranger the header.
        if bare.find(":") == 4 and bare[:2] in ("fc", "fd"):
            if all(ch in "0123456789abcdef" for ch in bare[2:4]):
                return True
        # fe80::/10 (link-local) is deliberately NOT here — see the module note.
        return False

    quad = _read_ipv4(host)
    if quad is not None:
        a, b = quad[0], quad[1]
        if a == 127:
            return True  # loopback 127.0.0.0/8
        if a == 10:
            return True  # private 10.0.0.0/8
        if a == 172 and 16 <= b <= 31:
            return True  # private 172.16.0.0/12
        if a == 192 and b == 168:
            return True  # private 192.168.0.0/16
        if a == 100 and 64 <= b <= 127:
            return True  # CGNAT 100.64.0.0/10
        # 169.254.0.0/16 is deliberately NOT here — see the module note.
        return False

    # A NUMERIC SPELLING WE DID NOT READ OURSELVES. `010.010.010.010` is octal
    # to the resolver and reaches 8.8.8.8; `134744072` and `0x08080808` reach
    # it too; `2852039166` reaches the metadata service. To the name-shaped
    # tests below, the last three look like single-label hostnames, which this
    # set calls internal — so a public address would be permitted under the
    # default. Refusing every numeric form the strict reader above declined is
    # the only answer that cannot disagree with the resolver.
    if _is_numeric_address_form(host):
        return False

    # A single-label name is a Docker Compose service, a Kubernetes short name,
    # an /etc/hosts entry — EXCEPT for the top-level domains that carry address
    # records of their own. Those resolve for anyone, so reading every dotless
    # name as internal would carry the header to a stranger.
    if "." not in host:
        return host not in PUBLIC_DOTLESS_HOSTS

    for suffix in INTERNAL_SUFFIXES:
        if host == suffix or host.endswith("." + suffix):
            return True
    return False


def should_propagate_to(host: Any) -> bool:
    """Decide whether the trace headers may be attached to a call to ``host``.

    ``host`` is the bare hostname — no scheme, no port, no path, no userinfo.
    It never leaves this stack: the answer is a boolean, and nothing about the
    destination is recorded, counted or uploaded by this module.

    Never raises. Anything it cannot judge is a refusal.
    """
    try:
        if not isinstance(host, str) or not host:
            return False
        policy = trace_propagation_policy()
        if policy.off:
            return False
        lower = host.lower()
        if policy.internal and is_internal_host(lower):
            return True
        if lower in policy.hosts:
            return True
        for suffix in policy.suffixes:
            if lower == suffix or lower.endswith("." + suffix):
                return True
        return False
    except Exception:  # noqa: BLE001
        return False


def host_of(target: Any) -> str:
    """The bare hostname of an outbound target, lowercased, or ``""``.

    Deliberately parser-free and allocation-cheap: strips a scheme, userinfo, a
    path, a query and a port by hand, so it costs the host nothing beyond a few
    slices on a string it already had. Accepts a full URL, an origin, a bare
    ``host:port``, or a bare host. Never raises.
    """
    try:
        if not isinstance(target, str) or not target:
            return ""
        text = target.strip()
        scheme = text.find("://")
        if scheme >= 0:
            text = text[scheme + 3 :]
        text = text.split("/", 1)[0].split("?", 1)[0]
        at = text.rfind("@")
        if at >= 0:
            text = text[at + 1 :]
        if text.startswith("["):
            close = text.find("]")
            if close > 0:
                return text[1:close].lower()
        # A BARE IPv6 LITERAL. A connection object hands its host over without
        # brackets, and splitting that on the first colon turned ``fe80::1``
        # into ``fe80`` and ``2001:4860:4860::8888`` into ``2001`` — both
        # single-label names, and a single-label name is internal by default.
        # The split therefore permitted every public IPv6 address there is.
        # Only ``host:port`` has exactly one colon: an unbracketed address with
        # more than one cannot be carrying a port.
        if text.count(":") > 1:
            return text.lower()
        return text.split(":", 1)[0].lower()
    except Exception:  # noqa: BLE001
        return ""


class PropagationDescription(NamedTuple):
    """What a customer surface shows: the rule in force, in the customer's own
    terms, with no host of theirs invented and none of ours assumed."""

    #: ``off``, ``internal`` (the default set only), or ``named``.
    mode: str
    #: True when the built-in non-public set is part of what is permitted.
    internal: bool
    #: The destinations the customer named, rendered back the way they wrote
    #: them — a suffix keeps its leading dot.
    named: tuple[str, ...]
    #: Entries that were not usable and were ignored.
    refused: tuple[str, ...]
    #: The setting's name, so a surface never hard-codes it.
    setting: str


def describe_trace_propagation() -> PropagationDescription:
    """Describe the policy in force for a customer-facing surface. Never raises."""
    try:
        policy = trace_propagation_policy()
    except Exception:  # noqa: BLE001
        policy = _OFF_POLICY
    named: tuple[str, ...] = tuple(policy.hosts) + tuple(
        "." + suffix for suffix in policy.suffixes
    )
    mode = "off" if policy.off else ("named" if named else "internal")
    return PropagationDescription(
        mode, policy.internal, named, tuple(policy.refused), PROPAGATION_ENV
    )


def propagated_header_items(
    headers: Any, already: Optional[Iterable[str]] = None
) -> list[tuple[str, str]]:
    """Filter a built header map down to the three that may cross a boundary.

    The propagation contract is "the existing trace headers", not "whatever the
    builder returns", so the caller passes the builder's output through here
    rather than iterating it. A header added to ``trace_headers`` for some
    other purpose must be added to the allow-list deliberately, by someone who
    has decided it may leave the process.

    ``already`` names headers the host set themselves, which are left exactly
    as they are: they may be forwarding a trace from somewhere the kit cannot
    see. Never raises; an unusable input yields an empty list, which attaches
    nothing.
    """
    from .span_scope import PARENT_HEADER
    from .trace import ELAPSED_HEADER, TRACE_HEADER

    allowed = (TRACE_HEADER, ELAPSED_HEADER, PARENT_HEADER)
    try:
        seen = {name.lower() for name in (already or ())}
        out: list[tuple[str, str]] = []
        for name in allowed:
            if name in seen:
                # The host already set this one. Adding a second copy would
                # reach the destination as a two-value header rather than a
                # correction.
                return []
            value = headers.get(name)
            if isinstance(value, str) and value:
                out.append((name, value))
        return out
    except Exception:  # noqa: BLE001
        return []


#: How many named destinations a one-line summary spells out before it stops
#: counting. A status row is one line; a customer with forty entries needs the
#: shape of the answer, not the list.
SUMMARY_NAMED_LIMIT = 4


def trace_propagation_summary() -> str:
    """ONE SENTENCE SAYING WHERE THE TRACE IS BEING PASSED ON.

    The customer-visible answer to "is this happening, and to whom?", so the
    behaviour is inspectable rather than implicit. Rendered by the kit's status
    page; the Node kit's ``tracePropagationSummary`` produces the same words
    from the same policy, and the two are held to each other by
    ``scripts/src/__tests__/trace-propagation-parity.test.ts``.

    NAMES ONLY WHAT THE CUSTOMER TYPED. The built-in set is described in words
    rather than listed, because it is a rule about addresses, not a list of
    hosts — and because a kit that printed the hosts it had decided were
    internal would be printing the app's own topology onto a page. Never
    raises.
    """
    try:
        d = describe_trace_propagation()
    except Exception:  # noqa: BLE001
        return "Off — no trace headers are attached to outgoing calls"
    ignored = ""
    if d.refused:
        more_refused = ", …" if len(d.refused) > SUMMARY_NAMED_LIMIT else ""
        ignored = (
            " (ignored, not a hostname: "
            + ", ".join(d.refused[:SUMMARY_NAMED_LIMIT])
            + more_refused
            + ")"
        )
    if d.mode == "off":
        return f"Off — no trace headers are attached to outgoing calls{ignored}"
    shown = ", ".join(d.named[:SUMMARY_NAMED_LIMIT])
    more = (
        f" and {len(d.named) - SUMMARY_NAMED_LIMIT} more"
        if len(d.named) > SUMMARY_NAMED_LIMIT
        else ""
    )
    if d.mode == "internal":
        return f"Internal destinations only — the default{ignored}"
    if d.internal:
        return f"Internal destinations, plus {shown}{more}{ignored}"
    return f"Only {shown}{more}{ignored}"


def headers_for_next_hop(
    host: Any, already: Optional[Iterable[str]] = None
) -> list[tuple[str, str]]:
    """The trace headers to attach to an outgoing call to ``host``, or nothing.

    The one entry point the outbound observers use, so the whole decision —
    is there a trace to forward, is this destination permitted, did the host
    already set the header — lives in one place and reads the same however the
    call was made.

    NEVER MINTS. Outside a request there is no hop for the next service to be a
    child of, and a minted id would tag an unrelated outgoing call with a brand
    new trace nothing else shares. ``trace_headers()`` mints by design, for a
    developer who is deliberately starting a trace; here, silence is correct.

    Never raises. Anything it cannot decide attaches nothing, which is exactly
    today's behaviour.
    """
    try:
        from .trace import current_trace_id, trace_headers

        if current_trace_id.get() is None:
            return []
        if not should_propagate_to(host):
            return []
        return propagated_header_items(trace_headers(), already)
    except Exception:  # noqa: BLE001
        return []
